name: CI

on:
  push:
    branches:
      - master
  pull_request: ~

jobs:

  pytest-linux:
    name: Run tests Python ${{ matrix.python-version }} (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        id: python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup environment
        run: |
          python -m pip install -U pip poetry
          poetry install
      - name: Run pytest
        run: |
          poetry run pytest -v tests/
